### ISSUE TITLE
Provide options for filling in forecast values

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/StormEvents#110]
Right now only the latest version of RMW forecast as the default for filling in missing OFCL values. Ideally we'd like to be able to have option of using the old method of keeping consistent radius, etc. as well as the newer options for RMW forecast, so that the user has the option of choosing which method to be used.

**Comment by SorooshMani-NOAA** [comment]
@WPringle I can takeover this item if you haven't yet started working on it.

**Comment by WPringle** [comment]
@SorooshMani-NOAA Sure thank you, I didn't start on it so if you have an idea in mind how to do please go ahead and I will review.
