### ISSUE TITLE
Building docs fails

### ISSUE THREAD

**Issue by pmav99** [oceanmodeling/StormEvents#42]
There are 2 issues.

1. `dunamai` is not in pyproject.toml
2. the following throws a traceback:
```
$ cd docs
$ make html
        
Running Sphinx v5.0.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/panos/Prog/git/StormEvents/.venv/lib/python3.10/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/panos/Prog/git/StormEvents/docs/source/conf.py", line 45, in <module>
    metadata = config.read_configuration('../../setup.cfg')['metadata']
  File "/home/panos/Prog/git/StormEvents/.venv/lib/python3.10/site-packages/setuptools/config.py", line 81, in read_configuration
    raise DistutilsFileError('Configuration file %s does not exist.' % filepath)
distutils.errors.DistutilsFileError: Configuration file /home/panos/Prog/git/StormEvents/setup.cfg does not exist.

```

Possible solutions:

1. Re-introducing `setup.cfg`. I wouldn't add a new file just for this
2. hardcoding the `author` and `project` values in `conf.py` https://github.com/oceanmodeling/StormEvents/blob/4d9cfc5135fcb77eb70fb8e8924718e24626bf5d/docs/source/conf.py#L47-L48
3. Using `importlib.metadata`. Something like this should do it:

``` python
import importlib.metadata 

metadata = importlib.metadata.metadata("StormEvents")
author = metadata["Author"]
project = metadata["Name"]
```

TBH, I haven't tested if the last option works OK with readthedocs. It assumes that the package has been installed in site-packages and this might not be true in readthedocs. Moreover, for older python versions it requires a backport as an additional dependency : https://pypi.org/project/importlib-metadata/

**Comment by zacharyburnett** [comment]
there's an even simpler solution; we can just read directly from `pyproject.toml` to get the values:
https://github.com/oceanmodeling/StormEvents/blob/ae0558e91af966828aa92701efc5c147ea3fa670/docs/source/conf.py#L43-L46
