### ISSUE TITLE
lat and lon of CO-OPS stations are not accurate

### ISSUE THREAD

**Issue by BahramKhazaei-NOAA** [oceanmodeling/StormEvents#48]
I realized that lat and lon of CO-OPS stations are not taken very accurately with the StormEvents. I use the following command to retrieve the data:

`water_levels = coops_product_within_region(
                product='water_level',
                start_date = t0.isoformat(),
                end_date   = tend.isoformat(),
                region=box(*bnd)
                )`

**bnd = -99.0,5,-52.8,46.3**  covers Delaware Bay. One station in this domain is **Philadelphia, PA - Station ID: 8545240**.

- StormEvents coordinates are:
(39.9375, -75.125)

- CO-OPS coordinates (https://tidesandcurrents.noaa.gov/stationhome.html?id=8545240):
(39.9333, -75.1417)

Although that discrepancy is minimal and could not be very important for off-shore stations in deep ocean, it might have a significant impact for nearshore and river stations.

Another example in this domain is **Cape May, NJ - Station ID: 8536110** (https://tidesandcurrents.noaa.gov/stationhome.html?id=8536110). StormEvents coordinates are (38.96875, -74.9375) where actual coordinates are (38.9683, -74.9600).

**Comment by zacharyburnett** [comment]
@saeed-moghimi-noaa @BahramKhazaei-NOAA this should be fixed with pull request #49; it seems to have been an issue with casting to `float16` instead of `float32`, which was slightly altering the coordinates
