### ISSUE TITLE
Behavior of `start_time` and `end_time`

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/StormEvents#71]
@WPringle, @zacharyburnett, I'd like to discuss the intended, currently implemented, and expected behaviors of start and end time arguments for the `VortexTrack` here. 

My understanding is that `start_time` and `end_time` currently filters the dataframe entries (as accessed by `data` or written to file by `to_file`) only based on the `datetime`. For `BEST` track, `datetime` is equal to `track_start_time` so it **can be viewed** as filtering based on `track_start_time`. However, for forecast tracks, e.g. `OFCL`, where `datetime` is equal to the forecasted date, and **not** the `track_start_time` (i.e. advisory issuance time) the filtering happens based on the forecasted times.

Let's discuss the merits and issues of the current implementation and also talk about what would be a more desirable behavior for these inputs. @zacharyburnett if remember, can you please explain the logic behind the current implementation?

**Comment by zacharyburnett** [comment]
My original intent was for `.start_time` and `.end_time` to be transparent to the user, like you said, so that all functions and operations the user applied to the `VortexTrack` would use those times. Thus, for the forecasted tracks I would imagine that those filtered times should indicate the times within the track and ignore the issuance time.

**Comment by WPringle** [comment]
I tend to agree but the limitation with the forecasts is that there are many overlapping forecasts for the same set of datetimes. So I assume that for a forecast, the requested `start_time` indicates we would use the forecast that starts at that time, and then the `end_time` would be limited to up to 120 hours after that `start_time`. 
Or alternatively the we add a `forecast_time` that indicates the initial time of forecast to use and if `start_time` is some time before `forecast_time` then it grabs the analysis data between those dates.

**Comment by WPringle** [comment]
I actually like the idea of the second one come to think of it as it pretty much preserves the intended behavior of `start_time` and `end_time` as @zacharyburnett was saying.
