### ISSUE TITLE
`datetime` attribute of the advisory track in the written file is different from  the retrieved dataframe!

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [oceanmodeling/StormEvents#80]
I noticed that for a retrieved advisory track (i.e. `OFCL`) the `datetime` attribute in the dataframe for a given forecast is equal to the summation `datetime`  for `forecast_hours`=0, and the `forecast_hours`. BUT the `.to_file()` function only writes the first part as the `datetime`. As a result, several rows will have the same `datetime` values, but different `forecast_hours` values (see the screenshots below for `florence`, 2018). 
**Q#1**: Is there any reason for writing the `datetime` attribute in the file different from how it's been retrieved? 
**Q#2**: @pvelissariou1 which format is suitable for PaHM (the actual `datetime`, OR repeated `datetime` of `forecast_hours`=0)?

![image](https://github.com/oceanmodeling/StormEvents/assets/132295102/aa7ddd9b-b078-4ab9-97ba-0e3a1afb8bd5)

![image](https://github.com/oceanmodeling/StormEvents/assets/132295102/888f125f-9186-4d32-9b70-1ed5ed013a1b)

**Comment by FariborzDaneshvar-NOAA** [comment]
Per conversation with @pvelissariou1, for the forecast mode, it's been recommended to only use values for `forecast_hours`=0 and disregard the next `forecast_hours` (i.e. 3, 12, 24, ...) for a given `datetime`.
Is there a way to write only the values at the time of zero (something like the following lines) into a file? 
```
AL, 06, 2018083012, 03, OFCL,   0, ... 
AL, 06, 2018083018, 03, OFCL,   0, ... 
AL, 06, 2018083100, 03, OFCL,   0, ...
```

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA can we close this as a duplicate ticket since we're discussing everything related to datetime and formatting on #84 ?

**Comment by FariborzDaneshvar-NOAA** [comment]
Sure!

**Comment by FariborzDaneshvar-NOAA** [comment]
The second question was answered (see the note from Takis). 
See https://github.com/oceanmodeling/StormEvents/issues/84 for the response to the first question.
